### ISSUE TITLE
2022年4月26日発生の各種エラー状況の共有です

### ISSUE THREAD

**Issue by YutaroOgawa** [MicrosoftLearning/mslearn-dp100.ja-jp#1]
## 背景

小川雄太郎と申します（Azure MVP【AI】、MCT）（自己紹介：https://github.com/YutaroOgawa/about_me ）

2022年4月26日～28日のDP-100の3日間トレーニング（日本語）の講師を実施しています。
DP-100のJupyter Notebookの多くでエラーが発生したため、報告いたします。

## 要因
1. 2022年4月より、Azure ML Servicesが更新され、コンピューティングインスタンスを作成した際のデフォルトのPythonのバージョンが3.6から3.8へと変更されました
2. 2022年4月より、Azure ML Servicesが更新され、コンピューティングインスタンスを作成した際のデフォルトのAzure MLライブラリのバージョンが1.38から1.40.0へと変更されました

## 影響1
Notebookが「Python 3.6 Azure ML」カーネルで保存されているため、Python3.8のコンピューティングインスタンスでNotebookを開くと、
>「Kernel not found」Could not find a kernel matching Python 3.6 - AzureML. Please select a kernel:
と表示されます。

→【暫定対応】
エラーのモーダルで「Python 3.8 Azure ML 」を選択し、[Set Kearel]をクリックして、Jupyter Notebookを実行します

## 影響2
ScriptRunConfigクラスのコンストラクターのデフォルトパラメータが、変更されています。具体的には、v.1.38では
docker_runtime_config=DockerConfiguration(use_docker=True) 
がデフォルトでしたが、最新のv1.40ではdocker_runtime_config=Noneとなっています。

https://docs.microsoft.com/ja-jp/python/api/azureml-core/azureml.core.scriptrunconfig?view=azure-ml-py

→【対応】全JupyterNotebookのScriptRunConfigを使用する部分において、以下のように、
docker_runtime_config=DockerConfiguration(use_docker=True) 
のプロパティを必ず明示的に実装します。

```python
from azureml.core.runconfig import DockerConfiguration

# Create a script config
script_config = ScriptRunConfig(source_directory=experiment_folder,
                                script='diabetes_experiment.py',
                                environment=env,
                                docker_runtime_config=DockerConfiguration(use_docker=True))
```

## 影響3
pipコマンドの使用方法が変更されています。!pipとマジックコマンド!を入れていましたが、これではエラーとなるようになりました。
→【対応】 
!を外して、pip hogehogeとします

## 影響4
06 - Work with DataのJupyter Notebookにおいて

%%writefile $experiment_folder/diabetes_training.py
からはじまるセル

のblobでのファイル取得を以下に変更しました。

diabetes = run.input_datasets['training_data'].to_pandas_dataframe()

変更内容は英語版リポジトリ（4月に入って更新された最新版）と同じですので、そちらをご覧ください。

https://github.com/MicrosoftLearning/mslearn-dp100

---

以上、私が気付いた点となります。
なお、英語版のリポジトリは4月に入ってから上記がすべて修正されています。

上記以外にも私の見落としがあるかもしれませんが。気づいた情報の共有でした。
また、トレーニング時に修正指示として受講生に配布した資料も添付いたします。

[dp100_fix_20220426_.txt](https://github.com/MicrosoftLearning/mslearn-dp100.ja-jp/files/8563436/dp100_fix_20220426_.txt)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
Please help provide file path

**Comment by olprod** [comment]
Closed as no localization issues.
